### ISSUE TITLE
L530 only has Overheat and Signal Level entities

### ISSUE THREAD

**Issue by bwims** [petretiandrea/home-assistant-tapo-p100#257]
## Version of the custom_component

v1.2.15
(Home Assistant 2022.10.3)

## Configuration

```yaml
Not sure which logs you want.  I found this:
Logger: custom_components.tapo.common_setup
Source: helpers/update_coordinator.py:151
Integration: Tapo Controller (documentation, issues)
First occurred: 12 October 2022, 19:07:34 (12 occurrences)
Last logged: 18:48:09

Error fetching tapo data:
```

## Describe the bug

All the entities required to be useful are missing.   See image:
![image](https://user-images.githubusercontent.com/18516073/195672896-33f4d172-f48f-49d4-b1c1-e3bd3908a15d.png)

## Debug log

 I don't have a **logger**: entry  ...  what should it be set to?  

Also, I hate to appear dumb, but which logs precisely do you mean?  A cut and paste from Settings > System > Logs ?
Or a specific file from the system?

I'll be happy to provide what you need, but I need a little hand holding ... sorry!

```text

```
