### ISSUE TITLE
Automations won't execute

### ISSUE THREAD

**Issue by theoriginalcals** [petretiandrea/home-assistant-tapo-p100#315]
## Configuration

```yaml
alias: Bedtime Feed Button 3 Bedroom kkk
description: ""
trigger:
  - device_id: 5fad79862faeafbfc3deb7144850c33d
    domain: zha
    platform: device
    type: remote_button_short_press
    subtype: button_3
condition: []
action:
  - type: turn_on
    device_id: 2f16da64200173ee31486f6e99212169
    entity_id: light.hall_light
    domain: light
    brightness_pct: 5
  - type: turn_on
    device_id: f4a42af744ff14a318e78f8781afe9ce
    entity_id: light.lounge_lamp
    domain: light
    brightness_pct: 20
  - type: turn_on
    device_id: 32613080c008b2099a0c2d61e668f8ed
    entity_id: light.kitchen_light_strip
    domain: light
    brightness_pct: 11
mode: restart

```

## Describe the bug

No automations with any tapo bulb I have is running, or when it does jts say 1 out of 3. The device works when I then them on from Lovelace but not Via an automation.

## Debug log

This error originated from a custom integration.

Logger: custom_components.tapo.common_setup
Source: helpers/update_coordinator.py:168
Integration: Tapo Controller (documentation, issues)
First occurred: 31 December 2022 at 22:27:01 (3 occurrences)
Last logged: 07:55:46

Error fetching tapo data: Unexpected exception:

```
