### ISSUE TITLE
Current power condition reading error

### ISSUE THREAD

**Issue by azsdu** [petretiandrea/home-assistant-tapo-p100#351]
Hi everyone!

I am quite new at the whole Home Assistant features and I am just trying my wings, but my first automation does not want to work.
I want to make an automation, when I turn on the Tapo P110 wall plug with my scooter charger attached I want to read the current charging power with it. I figured out when it drops below 8 watts, after a short delay the scooter is fully charged.

## Version of the Home Assistant
Home Assistant OS Supervised
Version: core-2023.1.7
Operating System Version: 5.15.76-v8
Superviser Version: supervisor-2022.12.1
Agent Version: 1.4.1

## Version of the integration
Tapo controller from HACS
Version: v1.4.0

## Configuration
TP-Link Tapo P110
Name: Scooter Charger
Firmware: 1.1.6 Build 221114 Rel.203339
Hardware: 1.0 

The automation yaml:

```yaml
alias: Scooter charging
description: The scooter charger outlet turns off after the scooter is charged to 100%
trigger:
  - platform: device
    type: turned_on
    device_id: 609226b1b8b3404af9e9ba2dc231a1da
    entity_id: switch.scooter_charger
    domain: switch
condition:
  - type: is_power
    condition: device
    device_id: 609226b1b8b3404af9e9ba2dc231a1da
    entity_id: sensor.scooter_charger_current_power
    domain: sensor
    above: 1
    below: 8
action:
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
    enabled: true
  - type: turn_off
    device_id: 609226b1b8b3404af9e9ba2dc231a1da
    entity_id: switch.scooter_charger
    domain: switch
  - stop: Charge completed
mode: restart
```
/config/configuration.yaml:

```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
climate: !include climate.yaml

logger:
  default: error
  logs:
    custom_components.gree: debug
    custom_components.gree.climate: debug
```
/config/custom_components/tapo/sensors/sensor_config.py:
I have everything as original. Shoul I maybe change something here?

```yaml
from dataclasses import dataclass


@dataclass
class SensorConfig:
    name: str
    device_class: str
    state_class: str
    unit_measure: str

```

## Describe the bug
The problem is when I try to test the current power condition state in the automation it says "condition did not pass".
I tried to make it work with the numeric state condition, but that did not work, either. To me it looks like the value might not be a number but something else. 

On the Dashboard I can see the current values and states, so the communication works.

If I need to attach or describe something else please let me know.
(This is my first post here, so not entirely sure how things works)

Thank you for your help/advice!
