### ISSUE TITLE
P100, P110 overheat state in HA automation

### ISSUE THREAD

**Issue by mihing** [petretiandrea/home-assistant-tapo-p100#380]
## Version of the integration
1.6.0

## Configuration
p100, p110

```yaml
condition:
  - type: is_not_hot
    condition: device
    device_id: xxxx
    entity_id: binary_sensor.tp_socket_04_overheat
    domain: binary_sensor

```

## Describe the bug

HA automation expects a state of "off", but integration provides a value of "False".
Sorry for poor english. 

## Debug log

```text

type: is_not_hot
condition: device
device_id: xxxx
entity_id: binary_sensor.tp_socket_04_overheat
domain: binary_sensor

entity_id/0
Executed: 11:44:46
Result:

result: false
state: 'False'
wanted_state: 'off'

```
