### ISSUE TITLE
All (P100,P110) are recursively off - due to TapoError.INVALID_CREDENTIAL: 

### ISSUE THREAD

**Issue by frank777777** [petretiandrea/home-assistant-tapo-p100#552]
-->

## Version of the integration

I'm using the last one - I do always update

## Configuration

P100
P110

```yaml
Logger: homeassistant.config_entries
Source: config_entries.py:1248
First occurred: 19:22:29 (6 occurrences)
Last logged: 19:22:56

Config entry 'ale lamp' for tapo integration not ready yet: Returned error_code: TapoError.INVALID_CREDENTIAL: Invalid credentials; Retrying in background
Config entry 'schermophilipssalott' for tapo integration not ready yet: Returned error_code: TapoError.INVALID_CREDENTIAL: Invalid credentials; Retrying in background
Config entry 'ferro da stiro' for tapo integration not ready yet: Cannot connect to host 192.168.1.86:80 ssl:default [Connect call failed ('192.168.1.86', 80)]; Retrying in background
Config entry 'luce viale' for tapo integration not ready yet: Returned error_code: TapoError.INVALID_CREDENTIAL: Invalid credentials; Retrying in background
```

## Describe the bug

especially if the  wifi goes down ,  once back , in Home assistance  i loose all the connection - ( se image attached) 
and  there is no way to have it back 
PLEASE NOTE I assigned fixed IP via router .  

temporary workaround ( that might help understand) 
I do have to remove the appliance on Tapo App ONLY- 
then reconfigure , repair,  and  once back in the Tapo App, then goes at the right place even in HA. 
(but you do see the annoying part to reconfigure 32 plugs)

also note
In all cases I also tried to accept the MAC  option . ( knowing is beta) . 
but still the problem 

Francesco

```
![image](https://github.com/petretiandrea/home-assistant-tapo-p100/assets/110597948/3b7226f1-337a-4c0d-bb4a-fb85c6c8535e)
