### ISSUE TITLE
Hostname does not seem to be working

### ISSUE THREAD

**Issue by thomasaldershof** [petretiandrea/home-assistant-tapo-p100#802]
## Version of the integration

Integration version: 3.1.2

## Configuration

P115
by TP-Link
Firmware: 1.3.1
Hardware: 1.0
MAC: 30:DE:4B:89:9F:63

## Describe the bug

Whenever I try to use a hostname instead of an IP I get this error: "Failed setup, will retry Cannot connect to host <hostname>.internal:80 ssl:default [None]". I checked this in the browser and it gives a 200 Ok page. Using the IP does not produce any errors and works as expected.

## Debug log

I enabled logging with 
```
logger:
  default: error
  logs:
    custom_components.tapo.coordinators: info
```
but I see no logs being made from reloading or configuring the device.
